baseurl = "http://www.dc720.org"
languageCode = "en-us"
Title = "DEF CON Group 720 (Boulder, Co)"
# Copyright notice. This is displayer in the footer.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License, Credit where credit is due... the Potato-Dark theme (original theme before modifications) was created by surajmandalcell @ https://github.com/surajmandalcell/potato-dark"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  # twitter = "Your Twitter username"
  # facebook = "Your Facebook username"
  # instagram = "Your Instagram username"
  # googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
  # github = "Your GitHub username"
  # gitlab = "Your GitLab username"
  # npm = "Your npm username"
  # codepen = "Your CodePen username"
  # dribbble = "Your Dribbble username"
  # fivehundredpx = "Your 500px username" # 500px
  # flickr = "Your Flickr username"
  # pinterest = "Your Pinterest username"
  # tumblr = "Your Tumblr username"
  # vimeo = "Your Vimeo username"
  # youtube = "Your YouTube username"
  # linkedin = "Your LinkedIn username"
  # Disqus shortname
  # disqus = ""
  # Google Analytics API key.
  # ga_api_key = "Your Google Analytics tracking id"
  # Logo image. This is displayed ogp image.
  # logo = "/path/to/logo"
  # favicon = "/path/to/favicon"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Meeting"
    url = "/meeting"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

[[menu.main]]
    name = "Code of Conduct"
    url = "/codeofconduct"
    weight = 5

[[menu.main]]
    name = "FAQ"
    url = "/faq"
    weight = 6

[[menu.main]]
    name = "Topics"
    url = "/topics"
    weight = 7

[[menu.main]]
    name = "Meeting Notes"
    url = "/meetings"
    weight = 6

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
